// Code generated by protoc-gen-go. DO NOT EDIT.
// source: response.proto

package edgelab_adam_v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Response struct {
	Status               string             `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Error                string             `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Timestamp            string             `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Asset                string             `protobuf:"bytes,4,opt,name=asset,proto3" json:"asset,omitempty"`
	Currency             string             `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	Run                  *Run               `protobuf:"bytes,6,opt,name=run,proto3" json:"run,omitempty"`
	Results              map[string]float64 `protobuf:"bytes,7,rep,name=results,proto3" json:"results,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"fixed64,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_0fbc901015fa5021, []int{0}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Response) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *Response) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *Response) GetAsset() string {
	if m != nil {
		return m.Asset
	}
	return ""
}

func (m *Response) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *Response) GetRun() *Run {
	if m != nil {
		return m.Run
	}
	return nil
}

func (m *Response) GetResults() map[string]float64 {
	if m != nil {
		return m.Results
	}
	return nil
}

func init() {
	proto.RegisterType((*Response)(nil), "edgelab.adam.v1.Response")
	proto.RegisterMapType((map[string]float64)(nil), "edgelab.adam.v1.Response.ResultsEntry")
}

func init() { proto.RegisterFile("response.proto", fileDescriptor_0fbc901015fa5021) }

var fileDescriptor_0fbc901015fa5021 = []byte{
	// 246 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0x41, 0x6a, 0xf3, 0x30,
	0x10, 0x85, 0x91, 0xfd, 0xc7, 0x89, 0x27, 0x3f, 0x6d, 0x11, 0xa1, 0x08, 0xd3, 0x85, 0xe9, 0x22,
	0x78, 0x25, 0x68, 0xba, 0x29, 0x59, 0x75, 0xd3, 0x0b, 0xe8, 0x06, 0x4a, 0x32, 0x94, 0x52, 0x5b,
	0x36, 0x33, 0x52, 0xc0, 0x97, 0xea, 0x19, 0x8b, 0x25, 0xa7, 0x2d, 0xed, 0x6e, 0xbe, 0x79, 0xef,
	0xc1, 0xcc, 0x83, 0x2b, 0x42, 0x1e, 0x7a, 0xc7, 0xa8, 0x07, 0xea, 0x7d, 0x2f, 0xaf, 0xf1, 0xf4,
	0x8a, 0xad, 0x3d, 0x68, 0x7b, 0xb2, 0x9d, 0x3e, 0x3f, 0x54, 0x25, 0x05, 0x97, 0xb4, 0xfb, 0x8f,
	0x0c, 0x56, 0x66, 0xb6, 0xcb, 0x5b, 0x28, 0xd8, 0x5b, 0x1f, 0x58, 0x89, 0x5a, 0x34, 0xa5, 0x99,
	0x49, 0x6e, 0x60, 0x81, 0x44, 0x3d, 0xa9, 0x2c, 0xae, 0x13, 0xc8, 0x3b, 0x28, 0xfd, 0x5b, 0x87,
	0xec, 0x6d, 0x37, 0xa8, 0x3c, 0x2a, 0xdf, 0x8b, 0x29, 0x63, 0x99, 0xd1, 0xab, 0x7f, 0x29, 0x13,
	0x41, 0x56, 0xb0, 0x3a, 0x06, 0x22, 0x74, 0xc7, 0x51, 0x2d, 0xa2, 0xf0, 0xc5, 0x72, 0x0b, 0x39,
	0x05, 0xa7, 0x8a, 0x5a, 0x34, 0xeb, 0xdd, 0x46, 0xff, 0x3a, 0x5a, 0x9b, 0xe0, 0xcc, 0x64, 0x90,
	0xcf, 0xb0, 0x24, 0xe4, 0xd0, 0x7a, 0x56, 0xcb, 0x3a, 0x6f, 0xd6, 0xbb, 0xed, 0x5f, 0xef, 0xa5,
	0x00, 0x93, 0x8c, 0x2f, 0xce, 0xd3, 0x68, 0x2e, 0xb1, 0x6a, 0x0f, 0xff, 0x7f, 0x0a, 0xf2, 0x06,
	0xf2, 0x77, 0x1c, 0xe7, 0xa7, 0xa7, 0x71, 0xba, 0xfe, 0x6c, 0xdb, 0x80, 0xf1, 0x63, 0x61, 0x12,
	0xec, 0xb3, 0x27, 0x71, 0x28, 0x62, 0x6f, 0x8f, 0x9f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xec, 0x15,
	0xab, 0x21, 0x65, 0x01, 0x00, 0x00,
}
